default: zigzagConversion

zigzagConversion.o: zigzagConversion.c
	gcc -c zigzagConversion.c -o zigzagConversion.o
zigzagConversion: zigzagConversion.o
	gcc zigzagConversion.o -o zigzagConversion
clean:
	del zigzagConversion.o
	del zigzagConversion.exe