default: lengthOfLongestSubstring

lengthOfLongestSubstring.o: lengthOfLongestSubstring.c
	gcc -c lengthOfLongestSubstring.c -o lengthOfLongestSubstring.o
lengthOfLongestSubstring: lengthOfLongestSubstring.o
	gcc lengthOfLongestSubstring.o -o lengthOfLongestSubstring
clean:
	del lengthOfLongestSubstring.o
	del lengthOfLongestSubstring.exe