default: longestPalindrome

longestPalindrome.o: longestPalindrome.c
	gcc -c longestPalindrome.c -o longestPalindrome.o
longestPalindrome: longestPalindrome.o
	gcc longestPalindrome.o -o longestPalindrome
clean:
	del longestPalindrome.o
	del longestPalindrome.exe